"""Check catalogue and the mapping from research criteria to checks.

CHECKS: check id -> (pipeline level, kind, what it verifies).
MAP: criterion id (from research/HOW-TO-GIVE-GREAT-TALKS.md bullet order) -> (check ids, note).
Edit here; regenerate plan/levels/0-criteria.yml with `pipeline.py criteria`.
The ids follow bullet order, so inserting a bullet into the research shifts every id after it: re-audit the section when that happens.
Myths (section 7) map to N/A: an unsupported belief licenses nothing; the positive finding it contradicts is mapped under its own claim.
"""

CHECKS = {'M1': ('meta',
        'schema',
        'The idea statement is at most fifteen words, short enough to be repeated by someone who heard it once. The conclusions slide '
        'must show it verbatim and at least three slides must restate it.'),
 'M2': ('meta',
        'schema',
        'The audience is described: who they are, what they share, what they know, whether they read a picture unaided. Every later '
        'choice is made for this audience, so it has to be on paper first.'),
 'M3': ('meta',
        'script',
        'The take-home is a problem, a proof and an action, none of them a restatement of the one idea, and each is said somewhere in the notes, '
        'because a point the speaker never says cannot be taken home.'),
 'M4': ('meta',
        'schema',
        'There is a promise: what the listener will be able to do afterwards that they could not before. It is the reason to stay, and it '
        'must be said in the first ten minutes.'),
 'M5': ('meta',
        'schema',
        'What is and what could be are both written down, so the story can open on the gap between them and the middle can alternate '
        'across it.'),
 'M6': ('meta', 'schema', 'There is exactly one call to action, so the audience leaves with one thing to do rather than a list.'),
 'M7': ('meta',
        'schema',
        'The questions policy is decided: when the floor is open, whether the room is told, and what happens if someone asks anyway. '
        'It is said near the start only when the decision is to announce it.'),
 'M8': ('meta',
        'schema',
        'The slot is recorded: length, questions, buffer, time, whether it is filmed, the 16:9 shape, the speaking pace, and whether the '
        'talk exposes or teaches. The rest of the pipeline sizes itself from these.'),
 'M9': ('meta',
        'schema',
        'The speaker has used or built the thing: at least one piece of evidence of ownership, because competence is where confidence '
        'comes from.'),
 'M10': ('meta',
         'schema',
         'Someone other than the speaker gains from the idea. An idea that serves only the speaker is not worth a talk.'),
 'M11': ('meta', 'schema', 'The handout is something other than the slides, because slides that work as a handout do not work as slides.'),
 'M12': ('meta',
         'schema',
         'The contested points are decided and written down (opening joke and self-introduction, closing words, background, slide numbers, questions, pointer, tour coverage), so the '
         'deck and the notes follow one policy instead of drifting between the sides of a disagreement.'),
 'P1': ('plan',
        'script',
        'acts carry the story-spine beats in order: once upon a time, every day, until one day, because of that, until finally, ever since '
        'then'),
 'P2': ('plan', 'script', 'opening act has both sides of the gap; the middle crosses it at least twice, between acts or inside beats flagged contrast'),
 'P3': ('plan', 'schema', 'an explicit dramatic question in the opening act'),
 'P4': ('plan', 'script', 'at least one moment of change (a turn) in the middle'),
 'P5': ('plan', 'script', 'the insight answers the dramatic question outright, in words other than the idea statement, and is said in the notes'),
 'P6': ('plan', 'script', 'every act declares an arousal target; at least one act targets a high-arousal emotion; none targets sadness'),
 'P7': ('plan', 'script', 'exactly one star moment'),
 'P8': ('plan', 'schema', 'fence: what the idea is not, and what it is confused with'),
 'P9': ('plan', 'script', 'the one idea is restated in at least three acts (cycles_idea)'),
 'P10': ('plan', 'script', 'roadmap chapters, each with a mnemonic image asset that exists; at most five'),
 'P11': ('plan',
         'script',
         'the candidate dump is prose, at least twice the chapter points in weight; the documentation pages in nav.adoc count as candidates when the prose points at them, so the docs are referenced, not copied'),
 'P12': ('plan', 'script', 'every claim has at least one evidence item; items marked verify are verified before strict mode'),
 'P13': ('plan', 'script', 'at least one metaphor drawn from something the audience already knows'),
 'P14': ('plan', 'script', 'closing act references the opening beat (full circle)'),
 'P15': ('plan', 'schema', 'closing act has new_bliss text'),
 'P16': ('plan', 'schema', 'context (situate): the problem, who else works on it, why it matters'),
 'P17': ('plan', 'schema', 'memorability: symbol, surprise, salient idea; the slogan is the idea statement itself'),
 'P18': ('plan', 'script', "beat target minutes fit the meta file's talk minutes; beats without a target share the minutes the targets leave, in proportion to their notes"),
 'P19': ('plan', 'script', 'every beat has transition words, and the notes of its first slide contain them'),
 'P20': ('plan', 'script', 'every beat either carries at least one claim of its act or states its purpose (a transition, a demo, an ask), so no stretch of speech exists without a reason'),
 'P21': ('plan', 'script', 'a beat that explains a system names the earlier beat that introduced its parts'),
 'P22': ('plan',
        'script',
        'no beat longer than six minutes without a pause or a question to the room (segmenting is Mayer2003; the six-minute figure is a '
        'policy, not evidence)'),
 'P23': ('plan', 'script', 'at least one beat asks the room a question and waits (warns if absent)'),
 'P24': ('plan', 'script', 'at least two distinct media kinds across the talk (live page, code, diagram, image)'),
 'P25': ('plan', 'script', 'closing act has at least two beats and at least two minutes'),
 'P26': ('plan', 'script', 'a beat flagged establishes_vision starts within the first five minutes'),
 'P28': ('plan', 'script', 'every claim of an act is carried by at least one of its beats (the beat lists the claim ids it delivers), and beats name only claims that exist'),
 'S1': ('slides',
        'script',
        'first slide is the title card; conclusions slide is the last non-backup slide; call-to-action slide precedes it; after the conclusions only backups and a repeat of the title card, for after the questions'),
 'S2': ('slides',
        'script',
        'on-screen limits by kind: word ≤3 words, line ≤14 words, table ≤4x4, code ≤8 lines and ≤60 columns, list-like text forbidden'),
 'S3': ('slides', 'schema', 'every slide has exactly one assertion sentence'),
 'S4': ('slides',
        'script',
        'slide durations sum to the talk minutes within ten percent; no slide over 120 s; at least 20 slides (the count floor is a policy '
        'following Conway2014 and Phillips2014, both expert)'),
 'S5': ('slides', 'script', 'motion is declared only where it shows a relation (a morph sharing an element with the previous slide, or a named transition); a declared morph must share an element with its predecessor; every other slide uses the deck\'s default transition, which the audience reads as "next"'),
 'S6': ('slides', 'script', 'image and diagram slides carry the explanation in notes (≥12 words, a sentence) and at most 14 words on screen; example slides (code, snippet, rendered) are shown while a sentence is said and have no floor'),
 'S7': ('slides', 'script', 'every slide that is not an example carries at least twelve words of notes unless marked silent'),
 'S8': ('slides', 'script', 'every referenced asset file exists'),
 'S9': ('slides', 'script', 'no run of more than eight consecutive on-screen words appears verbatim in the notes (no transcript on screen)'),
 'S10': ('slides', 'schema', 'image slides declare image_role represents|explains; decorative is not a value'),
 'S11': ('slides', 'schema', 'diagram and chart slides declare labels integrated and a chart_kind with a rationale'),
 'S12': ('slides', 'script', 'a code slide with several highlight steps gives every step after the first its own notes; a step with several ranges is split'),
 'S13': ('slides', 'schema', 'code steps of at most forty lines each, in sequence; a longer file is shown as parts'),
 'S14': ('slides', 'script', 'backup slides only after the conclusions slide'),
 'S15': ('slides', 'script', "exactly one slide flagged star_moment, and it matches the story's"),
 'S16': ('slides', 'script', 'conclusions slide on-screen text is the one idea; it is not Questions? or Thank you'),
 'S17': ('slides', 'script', 'call-to-action slide carries a URL and a QR asset that exists'),
 'S18': ('slides', 'script', 'title card asset exists and is 16:9'),
 'S19': ('slides', 'script', 'at most one slide flagged deliberately_complex'),
 'S20': ('slides', 'script', 'at least three slides flagged restates_idea'),
 'S22': ('slides',
         'script',
         "banned phrases absent from notes: apologies, 'is the mic on', 'a lot to tell you', 'great question', 'I'm not good at this'"),
 'S23': ('slides', 'script', 'opening slide notes contain the promise, the questions policy when it is announced, and the applause/attention cue'),
 'S24': ('slides', 'script', 'no on-screen text of kind line ends with a question mark unless flagged hostile_audience'),
 'S25': ('slides', 'script', 'image and diagram slides declare emphasis: the element that is largest and why'),
 'S26': ('slides', 'script', "notes across the talk use inclusive 'we' at least ten times"),
 'S27': ('slides',
         'script',
         "speaking time implied by the notes at the meta speaking rate matches each slide's declared duration (within 0.6x to 1.6x) and "
         'the total matches the talk within 15%; the research offers only rules of thumb on time (a minute per slide, expert), so timing '
         'comes from the script, not from a rule'),
 'S29': ('slides', 'script', 'every beat has at least one slide, the slides of a beat are contiguous, and the beats appear in the deck in the order of the plan'),
 'H1': ('html', 'script', 'one top-level section per slide, same ids and order, notes present'),
 'H2': ('html', 'script', 'no <ul>/<ol> inside slide sections'),
 'H3': ('html', 'script', 'Reveal canvas is 16:9'),
 'H4': ('html',
        'script',
        "theme: base font at least 40px on the 1600 canvas (Winston2018's floor, expert), no uppercase transform outside covers, no italic "
        'runs, at most three typefaces'),
 'H5': ('html', 'script', 'theme hides controls, progress and slide number on covers and subdues them elsewhere'),
 'H6': ('html', 'script', 'no logo, title bar or header element in non-cover sections'),
 'H7': ('html', 'script', 'no per-slide background except the title card and live pages'),
 'H8': ('html', 'script', 'consecutive auto-animate sections share at least one data-id'),
 'H9': ('html',
        'script',
        'no <audio>, no autoplay video, transitions limited to none/fade/slide plus one zoom (decorative motion and sound are the '
        'seductive details of Mayer2003 and Kosslyn2012; the one-zoom allowance is a policy)'),
 'H10': ('html', 'script', 'contrast of text colours on the canvas ≥ 4.5:1, computed from CSS variables'),
 'H11': ('html', 'script', 'build produced index.html, a PDF, and a contact sheet'),
 'D1': ('logs', 'logged', 'at least three live, timed rehearsals within the slot, at least one to people who do not know the work'),
 'D2': ('logs', 'logged', 'at least one rehearsal recorded and reviewed, with captions check'),
 'D3': ('logs', 'logged', 'equipment tested; PDF and still-image backups listed; contingency for clicker failure'),
 'D4': ('logs', 'logged', 'room visited (warns if not yet)'),
 'D5': ('logs', 'logged', 'lights-up request recorded'),
 'D6': ('logs', 'logged', "pre-talk ritual includes the 'I am excited' relabel"),
 'D7': ('logs', 'logged', 'Q&A conduct checklist acknowledged'),
 'D8': ('logs', 'logged', 'feedback plan recorded'),
 'R1': ('reviews', 'review', 'narrative read-through: flow, one idea, no tangents, story causes not lists'),
 'R2': ('reviews', 'review', 'humour is inside a safe story, relevant, not at the open'),
 'R3': ('reviews', 'review', 'metaphors and examples are familiar to this audience'),
 'R4': ('reviews',
        'review',
        "each slide gives its point to a lapsed listener; nothing on screen you will not talk about; amount feels 'about right'"),
 'R5': ('reviews', 'review', 'delivery review of the recording: energy, eye contact, pace, hands, pauses, not reading'),
 'N/A': ('none',
         'informational',
         'descriptive or background claim, or a myth: a belief the research found unsupported. Refuting a belief creates no criterion; '
         'where a positive finding exists it is mapped under its own claim and the note says which.')}

MAP = {'C1-01': (['M1', 'P5', 'S16', 'S20'], 'the statement is the handle shown on the last slide; the insight is the same idea explained at the reveal'),
 'C1-02': (['M4', 'M5', 'M10'], 'implied: a promise to the audience, a take-home for the audience and a benefit to the audience leave nobody else to be the hero; no field of its own'),
 'C1-03': (['N/A'], 'background'),
 'C1-04': (['M9', 'R5'], ''),
 'C1-05': (['M8'], 'mode=expose'),
 'C1-06': (['M2', 'M3'], ''),
 'C1-07': (['M10'], 'idea.benefit'),
 'C1-08': (['M11', 'S14'], 'the docs site is the handout; what the tour visits is the plan, not a checked property'),
 'C1-09': (['M2'], ''),
 'C1-10': (['P13', 'R3'], ''),
 'C1-11': (['S2', 'S9', 'R1'], ''),
 'C1-12': (['S26'], ''),
 'C1-13': (['N/A'], 'the talk does the work; no artefact'),
 'C1-14': (['P6'], ''),
 'C1-15': (['N/A'], 'consequence, not an action'),
 'C2-1-01': (['M1', 'S16'], ''),
 'C2-1-02': (['P11'], 'candidate dump recorded in story.yml'),
 'C2-1-03': (['P11', 'R1'], ''),
 'C2-1-04': (['M5', 'P2'], ''),
 'C2-1-05': (['P3', 'P4', 'P5', 'P6'], 'the revealed point is the insight, said outright at the reveal'),
 'C2-1-06': (['M3'], ''),
 'C2-1-07': (['M3', 'P20'], 'three points or nothing; and a beat with nothing to deliver and no purpose is talking without something to say'),
 'C2-2-01': (['R1'], 'first sixty words of the opening reviewed'),
 'C2-2-02': (['P1', 'D1'], 'opening rehearsed in every session'),
 'C2-2-03': (['P3', 'P2'], ''),
 'C2-2-04': (['M4', 'S23'], ''),
 'C2-2-05': (['P10'], ''),
 'C2-2-06': (['P1'], 'opener_type enumerated in the opening act'),
 'C2-2-07': (['P1'], 'opener_type enumerated in the opening act'),
 'C2-2-08': (['M12', 'R2'], 'policy: opening.joke false, no joke in the first two beats'),
 'C2-2-09': (['P1'], 'opener_type enumerated in the opening act'),
 'C2-2-10': (['M9', 'R5'], ''),
 'C2-2-11': (['M7', 'S23'], 'policy: not announced; at CppCon questions wait for the end by convention and nobody says so, so saying so would read as odd'),
 'C2-2-12': (['P26'], ''),
 'C2-2-13': (['S23', 'M12'], 'policy: opening.self_introduction false; the cue is checked in the first two slides'),
 'C2-2-14': (['S22'], ''),
 'C2-2-15': (['R2'], ''),
 'C2-3-01': (['P1', 'P11', 'R1'], ''),
 'C2-3-02': (['P2'], ''),
 'C2-3-03': (['P12'], ''),
 'C2-3-04': (['P9', 'S20'], ''),
 'C2-3-05': (['P8'], ''),
 'C2-3-06': (['P19', 'S29'], 'the deck follows the plan beat by beat, so the spoken structure and the shown structure are one'),
 'C2-3-07': (['P10', 'P19'], ''),
 'C2-3-08': (['P24'], ''),
 'C2-3-09': (['P7', 'S15'], ''),
 'C2-3-10': (['R4'], 'emotion cue on the star slide'),
 'C2-3-11': (['P13'], ''),
 'C2-3-12': (['S3', 'R4'], ''),
 'C2-3-13': (['P12', 'P28'], 'every claim has evidence and is carried by a beat'),
 'C2-3-14': (['P23'], ''),
 'C2-3-15': (['P22'], ''),
 'C2-3-16': (['P22'], 'pause markers on beats'),
 'C2-3-17': (['P21'], ''),
 'C2-3-18': (['P16'], ''),
 'C2-3-19': (['P17'], ''),
 'C2-3-20': (['D3'], 'clicker contingency'),
 'C2-4-01': (['S16', 'S20'], ''),
 'C2-4-02': (['M6', 'S17'], ''),
 'C2-4-03': (['P15'], ''),
 'C2-4-04': (['P14', 'S16'], ''),
 'C2-4-05': (['P25'], ''),
 'C2-4-06': (['S1', 'S16'], ''),
 'C2-4-07': (['M12'], 'policy: closing words decided and checked in the last notes'),
 'C3-1-01': (['S2', 'S6', 'S7'], ''),
 'C3-1-02': (['N/A'], 'mechanism'),
 'C3-1-03': (['S6'], ''),
 'C3-1-04': (['S9'], ''),
 'C3-1-05': (['S2'], ''),
 'C3-1-06': (['S2'], 'word and line kinds allowed'),
 'C3-1-07': (['R4'], 'expert audience: notes add what the picture does not'),
 'C3-1-08': (['S2'], ''),
 'C3-1-09': (['S9', 'R5'], ''),
 'C3-1-10': (['H6', 'H7'], ''),
 'C3-2-01': (['S3'], ''),
 'C3-2-02': (['N/A'], 'supports S3'),
 'C3-2-03': (['S24'], ''),
 'C3-2-04': (['N/A'], 'mechanism'),
 'C3-2-05': (['S2', 'S3'], 'one sentence as assertion, none in the body'),
 'C3-2-06': (['S2', 'S4', 'H2'], ''),
 'C3-2-07': (['S3'], ''),
 'C3-2-08': (['N/A'], 'background'),
 'C3-2-09': (['N/A'], 'background'),
 'C3-3-01': (['H1', 'S3', 'S4'], ''),
 'C3-3-02': (['H6', 'H7', 'H4'], ''),
 'C3-3-03': (['S2', 'S3'], 'a slide is a figure: one message, no superfluous elements'),
 'C3-3-04': (['S2', 'S4'], ''),
 'C3-3-05': (['N/A'], 'rationale for S2/S6: fewer words alone is not the lever'),
 'C3-3-06': (['S27', 'S4'],
             'the minute-per-slide figure is an expert rule of thumb for text slides; for word and picture slides the time is what the '
             'notes take to say, which S27 estimates'),
 'C3-3-07': (['S2', 'S4'], ''),
 'C3-3-08': (['S2'], ''),
 'C3-3-09': (['S2'], ''),
 'C3-3-10': (['S2'], ''),
 'C3-3-11': (['S9', 'R4'], ''),
 'C3-3-12': (['H11'], 'the contact sheet is the heaviness test'),
 'C3-3-13': (['H9', 'S10'], ''),
 'C3-3-14': (['R4'], ''),
 'C3-3-15': (['S19'], ''),
 'C3-3-16': (['H2'], 'no bullet lists exist to build one at a time'),
 'C3-4-01': (['H8', 'S5'], ''),
 'C3-4-02': (['S5', 'S6'], ''),
 'C3-4-03': (['S12', 'S13'], ''),
 'C3-4-04': (['S10', 'S8'], ''),
 'C3-4-05': (['S13', 'H9'], 'paced discrete steps, no autoplay'),
 'C3-4-06': (['H9'], ''),
 'C3-4-07': (['S11'], ''),
 'C3-4-08': (['S12', 'M12'], 'policy: pointer digital; highlights on the slide do the pointing (S12), and the research argues against a laser because it turns the speaker to the screen, which a digital pointer does not'),
 'C3-4-09': (['N/A'], 'contested claim, recorded; controlled evidence preferred'),
 'C3-4-10': (['S11'], ''),
 'C3-4-11': (['S25'], ''),
 'C3-5-01': (['H4'], ''),
 'C3-5-02': (['H4', 'H10'], ''),
 'C3-5-03': (['H3', 'H4', 'H5', 'H7', 'S18'], ''),
 'C3-5-04': (['M12'], 'background decided in DESIGN-NOTES'),
 'C3-5-05': (['H9'], ''),
 'C3-5-06': (['H6'], 'custom theme, no default master'),
 'C3-6-01': (['R4'], 'props optional; reviewed for the star moment'),
 'C3-6-02': (['R4'], 'props optional; reviewed for the star moment'),
 'C3-6-03': (['R4'], 'props optional; reviewed for the star moment'),
 'C4-01': (['R5', 'D2'], ''),
 'C4-02': (['R5', 'D2'], ''),
 'C4-03': (['R5', 'D2'], ''),
 'C4-04': (['R5', 'D2'], ''),
 'C4-05': (['R5', 'D2'], ''),
 'C4-06': (['R5', 'D2'], ''),
 'C4-07': (['R5', 'D2'], ''),
 'C4-08': (['R5'], ''),
 'C4-09': (['S9', 'R5'], ''),
 'C5-01': (['S14', 'D7'], ''),
 'C5-02': (['D7'], 'black the screen for discussion: checklist'),
 'C5-03': (['M7', 'S23'], 'policy: ten reserved minutes at the end; an interruption is answered briefly and the time comes out of the end'),
 'C5-04': (['D7'], ''),
 'C5-05': (['D7'], ''),
 'C5-06': (['D7'], ''),
 'C5-07': (['D7'], ''),
 'C5-08': (['D7'], ''),
 'C5-09': (['S1', 'S16'], ''),
 'C6-1-01': (['S3'], ''),
 'C6-1-02': (['N/A'], 'the level order of this pipeline is the enforcement'),
 'C6-1-03': (['M9'], ''),
 'C6-1-04': (['N/A'], 'this pipeline is the checklist'),
 'C6-2-01': (['S27', 'S4', 'D1', 'P18'], ''),
 'C6-2-02': (['D1'], ''),
 'C6-2-03': (['D2'], ''),
 'C6-2-04': (['R5'], 'delivery discipline, judged on the recording'),
 'C6-2-05': (['D1'], 'issues recorded per rehearsal'),
 'C6-2-06': (['D1'], 'issues recorded per rehearsal'),
 'C6-3-01': (['D6'], ''),
 'C6-3-02': (['D6'], ''),
 'C6-3-03': (['D6'], ''),
 'C6-4-01': (['D3', 'H11'], ''),
 'C6-4-02': (['D4'], ''),
 'C6-4-03': (['D5'], ''),
 'C6-4-04': (['N/A'], 'slot is fixed by the conference'),
 'C6-4-05': (['N/A'], 'background'),
 'C6-4-06': (['D3'], 'logistics fields in the checklist'),
 'C6-4-07': (['D3'], 'logistics fields in the checklist'),
 'C6-4-08': (['D8'], ''),
 'C7-01': (['N/A'],
           "unsupported belief; no segmentation rule follows from it (P22's pacing comes from C2-3-15, and its threshold is a policy)"),
 'C7-02': (['N/A'], 'unsupported belief; the positive finding (relabel as excitement) is C6-3-01 -> D6'),
 'C7-03': (['N/A'], 'unsupported figure; the four-unit limit is C3-3-09 -> S2'),
 'C7-04': (['N/A'], 'unsupported belief; the pipeline itself is the response'),
 'C7-05': (['N/A'], 'unsupported belief; the positive finding (informative motion is preferred) is C3-4-01 -> S5'),
 'C7-06': (['N/A'], 'unsupported belief; what worked is C3-2-01 (assertion over evidence) and C3-1-03 (speech instead of text)'),
 'C7-07': (['N/A'], 'overstated belief; the positive finding (a few words help) is C3-1-05 -> S2'),
 'C7-08': (['N/A'], 'unsupported belief; the positive findings are C3-1-04 -> S9 and C3-2-01 -> S3'),
 'C7-09': (['N/A'], 'unsupported belief; the positive finding (sentence headline recalls better) is C3-2-03 -> S24'),
 'C7-10': (['N/A'], 'unsupported belief; the positive finding (coherence) is C3-3-13 -> S10, H9'),
 'C7-11': (['N/A'],
           'unsupported belief, and only that: the research says explanatory animation is not proven better, not that it is worse. '
           'Informative motion (magic move) is encouraged under C3-4-01 -> S5; decorative motion is limited under C3-4-06 -> H9. Nothing '
           'follows from the myth itself.'),
 'C7-12': (['N/A'], 'unsupported figure; the limit used (four) is C3-3-09 -> S2'),
 'C7-13': (['N/A'], 'unsupported claim; nothing to do'),
 'C7-14': (['N/A'], 'unsupported belief; R1 judges the talk on its own terms, not against a formula'),
 'C7-15': (['N/A'], 'weak evidence; the deck has no bullets for other reasons (C3-2-06 -> H2)'),
 'C7-16': (['N/A'], 'background'),
 'C7-17': (['N/A'], 'background')}
